/**
 * render-readme.ts
 * ------------------------------------------------------------------
 * README SYSTEM
 *
 * Reads README.template.md, replaces each PANEL marker block with an
 * <img> embed pointing (by relative repo path) at the corresponding
 * generated SVG, and writes the result to README.md. The profile
 * README renderer strips <script>/<style> outside images but honours
 * animation *inside* an <img>-embedded SVG, which is why every panel
 * is a self-contained animated SVG rather than inline markup.
 * ------------------------------------------------------------------
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { DeveloperIdentity } from "./types.js";

// SVGs are referenced by RELATIVE repo path, not an absolute raw URL.
// Two reasons this is the correct choice:
//   1. GitHub proxies README images through camo.githubusercontent.com,
//      which strips query strings and caches on the *content hash*. So a
//      "?cache=timestamp" param does nothing except pollute every commit
//      with a spurious diff — which would defeat the whole diff-gating
//      strategy. Cache-busting happens automatically: when the SVG bytes
//      change, Camo's hash changes, and the new image is fetched.
//   2. Relative paths render on the profile page and in local previews
//      without hardcoding the branch or username into every <img>.
function assetPath(filename: string): string {
  return `assets/svg/${filename}`;
}

function imgPanel(filename: string, alt: string): string {
  return `<img src="${assetPath(filename)}" alt="${alt}" width="100%" />`;
}

function replacePanel(html: string, name: string, content: string): string {
  const re = new RegExp(`<!--PANEL:${name}:START-->[\\s\\S]*?<!--PANEL:${name}:END-->`);
  return html.replace(
    re,
    `<!--PANEL:${name}:START-->\n${content}\n<!--PANEL:${name}:END-->`
  );
}

function replaceIdentityField(html: string, field: string, value: string): string {
  const re = new RegExp(`<!--IDENTITY:${field}-->`, "g");
  return html.replace(re, value);
}

function buildSummary(identity: DeveloperIdentity): string {
  const topLangs = identity.languageFingerprint
    .slice(0, 3)
    .map((l) => `${l.language} (${l.percentage}%)`)
    .join(", ");
  const clusterLine =
    identity.projectClusters.length > 0
      ? `Work spans ${identity.projectClusters.length} project cluster${
          identity.projectClusters.length === 1 ? "" : "s"
        }: ${identity.projectClusters.map((c) => c.label).join(", ")}.`
      : "";

  return [
    `${identity.repositoryGraph.nodes.length} repositories tracked · ${identity.activityMap.totalContributions} contributions in the last year · account age ${Math.floor(
      identity.accountAgeInDays / 30
    )} months.`,
    topLangs ? `Primary languages: ${topLangs}.` : "",
    clusterLine,
    identity.achievements.length > 0 ? `Achievements: ${identity.achievements.join(", ")}.` : "",
  ]
    .filter(Boolean)
    .join("\n\n");
}

async function main() {
  const [template, identity]: [string, DeveloperIdentity] = await Promise.all([
    readFile(path.resolve("README.template.md"), "utf-8"),
    readFile(path.resolve("data/cache/identity.json"), "utf-8").then((s) => JSON.parse(s)),
  ]);

  let html = template;

  // Strip the leading "SOURCE template" HTML comment — it's guidance for
  // whoever edits the template, not something that belongs in the rendered
  // profile README. Replace it with a short auto-generated banner instead.
  html = html.replace(/^<!--[\s\S]*?-->\s*/, "");
  html =
    `<!-- AUTO-GENERATED by scripts/render-readme.ts. Edit README.template.md, not this file. -->\n\n` +
    html;

  html = replaceIdentityField(html, "displayName", identity.displayName ?? identity.login);
  html = replaceIdentityField(html, "login", identity.login);
  html = replaceIdentityField(html, "generatedAt", identity.generatedAt);

  html = replacePanel(html, "SUMMARY", buildSummary(identity));
  html = replacePanel(html, "HEATMAP", imgPanel("heatmap.svg", "Contribution activity map"));
  html = replacePanel(html, "COUNTERS", imgPanel("counters.svg", "Live counters"));
  html = replacePanel(html, "NETWORK", imgPanel("network-graph.svg", "Repository network graph"));
  html = replacePanel(html, "TIMELINE", imgPanel("timeline.svg", "Repository timeline"));
  html = replacePanel(html, "LANGUAGE", imgPanel("language-fingerprint.svg", "Language fingerprint"));
  html = replacePanel(html, "FLOW", imgPanel("activity-flow.svg", "Activity flow"));

  await writeFile(path.resolve("README.md"), html, "utf-8");
  console.log("[render-readme] README.md regenerated.");
}

main().catch((err) => {
  console.error("[render-readme] failed:", err);
  process.exit(1);
});
